### PR TITLE
Adds tree data structure functionality

### PR DESCRIPTION
**Pull request by katesmatthews**
Adds functionality in projectController.js to build tree structure out of database info.

### CODE REVIEW

**Review by AlenaBudzko — DISMISSED** [review]
Approved.

**Review by conor-jh — CHANGES_REQUESTED** [review]
Let’s keep this test file out of the actual repo

**Review by conor-jh — APPROVED** [review]
Looks good 👍

**Review by AlenaBudzko — APPROVED** [review]
Approved.

**Pull request merged**
